// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR';
export const SIGNOUT_USER = 'SIGNOUT_USER';

// request actions
export const LOAD_REQUESTS_SUCCESSFUL = 'LOAD_REQUESTS_SUCCESSFUL';
export const LOAD_REQUEST_SUCCESS = 'LOAD_REQUEST_SUCCESS';
export const REQUEST_ERRORS = 'REQUEST_ERRORS';
export const CREATE_REQUEST_SUCCESSFUL = 'CREATE_REQUEST_SUCCESSFUL';
